### ISSUE TITLE
Les horaires ne correspondent pas !

### ISSUE THREAD

**Issue by vianney-herve** [AquaBx/Esir-21-22-website#5]
strange, sans doute que le bot de Leo utilise pas ton module à jour, faudrait voir à modifier ça !

![image](https://user-images.githubusercontent.com/105049233/188073130-7ee7c2e6-dd9d-4849-8e8b-e9beed992fb5.png)

![image](https://user-images.githubusercontent.com/105049233/188073285-2e493547-30b0-4404-8939-0786bc544d9c.png)

**Comment by AquaBx** [comment]
Oui il est pas a jour le sien

**Comment by vianney-herve** [comment]
ok, tu peux close quand tu veux !

**Comment by AquaBx** [comment]
Il est entrain de fixer,  je close
