### ISSUE TITLE
Comportement flèche retour en arrière sur téléphone

### ISSUE THREAD

**Issue by Astri2** [AquaBx/Esir-21-22-website#6]
Android 12, Chrome

le bouton de retour en arrière (bouton < ) sur téléphone ne marche pas toujours comme il devrait à priori le faire.

reproduire : 
partir de la page d'accueil, descendre dans l'arborescence des cours, appuyer sur la flèche retour en arrière.
La page devrait soit ne pas changer, soit revenir de plusieurs pages en arrière si l'ont appuie un grand nombre de fois.

**Comment by AquaBx** [comment]
le 1 ou le 2 (je suis sur ordi mais sur tel c'est presque pareil)
![image](https://user-images.githubusercontent.com/35542432/188618428-03c3bf21-09b6-45f2-82a7-a59746ef8183.png)

**Comment by Astri2** [comment]
j'aurais tendance à dire le 1, je sais pas à quoi correspond le 2.. c'est pas la flèche du site, mais celle du téléphone

**Comment by AquaBx** [comment]
oui c'est ça, c'est totalement bugué aussi sur ordi

**Comment by AquaBx** [comment]
j'ai trouvé le soucis je build et tu me redis

**Comment by AquaBx** [comment]
c'est build tu peux vérifier

**Comment by vianney-herve** [comment]
est-ce que le bug c'est que tu ne peux plus relancer l'app après avoir appuyé sur la flèche retour lorsque tu étais sur l'accueil ?
